primeiraNota = int(input("Digite a primeira nota: "))
segundaNota = int(input("Digite a segunda nota: "))
terceiraNota = int(input("Digite a terceira nota: "))
quartaNota = int(input("Digite a quarta nota: "))
media = float((primeiraNota + segundaNota + terceiraNota + quartaNota) / 4)
print("A média aritmética é", media)
